version: '3'
services:
  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "demo-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
    ports:
      - "8080:8080"
    depends_on:
      - collector

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    expose:
      - "4317"
    ports:
      - "4317"  # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one