receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: DEBUG
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  zipkin:
    endpoint:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging, jaeger]
    logs:
      receivers: [otlp]
      exporters: [logging]